[build]
  command = "yarn install && yarn build:netlify"
  publish = "build"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.22"
  CI = "false"
  GENERATE_SOURCEMAP = "false" 